# fly.toml app configuration file generated for no-css-message-board on 2023-09-18T16:54:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "no-css-message-board"
primary_region = "otp"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
